[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/"
]
optimizer = true
optimizer_runs = 200

[rpc_endpoints]
mainnet = "https://eth-mainnet.g.alchemy.com/v2/${ALCHEMY_KEY}"
op = "https://mainnet.optimism.io"
op_sepolia = "https://sepolia.optimism.io"
sepolia = "https://eth-sepolia.g.alchemy.com/v2/${ALCHEMY_KEY}"

[etherscan]
mainnet = { key = "${ETHERSCAN_KEY}" }
op = { key = "${OPTIMISTIC_ETHERSCAN_KEY}" }
op_sepolia = { key = "${OPTIMISTIC_ETHERSCAN_KEY}" }
