[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "forge-std/=lib/forge-std/src/"
]
optimizer = true
optimizer_runs = 200
fs_permissions = [{ access = "read", path = "./data" }]

[rpc_endpoints]
mainnet = "https://eth-mainnet.g.alchemy.com/v2/${ALCHEMY_KEY}"
op = "https://mainnet.optimism.io"

[etherscan]
mainnet = { key = "${ETHERSCAN_KEY}", url = "https://api.etherscan.io/api" }
op = { key = "${ETHERSCAN_KEY}", url = "https://api-optimistic.etherscan.io/api" }
